version: 0.2

env:
  variables:
    PROFILE: dev
    AWS_REGION_NAME: ap-northeast-2
    ECR_REPOSITORY_NAME: 
    REPOSITORY_URI: 
    DOCKER_BUILDKIT: "1"

phases:
  install:
    runtime-versions:
      docker: 20

  pre_build:
    commands:
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
      - aws ecr --region ${AWS_REGION_NAME} get-login-password | docker login --username AWS --password-stdin https://${REPOSITORY_URI}
      # 태그 이름에 Git 커밋 해시를 이용
      - IMAGE_TAG=$(echo ${CODEBUILD_RESOLVED_SOURCE_VERSION} | cut -c 1-7)

  build:
    commands:
      - docker image build -t ${REPOSITORY_URI}:${IMAGE_TAG} .

  post_build:
    commands:
      - docker image push ${REPOSITORY_URI}:${IMAGE_TAG}
      - printf '{"name":"%s","ImageURI":"%s"}' $ECR_REPOSITORY_NAME $REPOSITORY_URI:$IMAGE_TAG > imageDetail.json

artifacts:
  files:
    - imageDetail.json