import { Html, Main, Head, NextScript } from 'next/document'

const Document = () => {
  return (
    <Html>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="stylesheet"
          as="style"
          href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.6/dist/web/static/pretendard-dynamic-subset.css"
        />
      </Head>

      <body>
        <div id="drawer"></div>

        <Main />
        <NextScript />
      </body>
    </Html>
  )
}

export default Document
